# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Selection_tree_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Selection_tree(object):
    def setupUi(self, Selection_tree):
        Selection_tree.setObjectName("Selection_tree")
        Selection_tree.resize(800, 380)
        font = QtGui.QFont()
        font.setPointSize(15)
        Selection_tree.setFont(font)
        Selection_tree.setStyleSheet("background-color: rgb(55,179,74);")
        self.centralwidget = QtWidgets.QWidget(Selection_tree)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_To_zhidkoe = QtWidgets.QPushButton(self.centralwidget)
        self.btn_To_zhidkoe.setGeometry(QtCore.QRect(20, 120, 370, 160))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_To_zhidkoe.setFont(font)
        self.btn_To_zhidkoe.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #00f500;\n"
"}")
        self.btn_To_zhidkoe.setObjectName("btn_To_zhidkoe")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 20, 800, 80))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setIndent(7)
        self.label.setObjectName("label")
        self.btn_To_gazoobraznoe = QtWidgets.QPushButton(self.centralwidget)
        self.btn_To_gazoobraznoe.setGeometry(QtCore.QRect(410, 120, 370, 160))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btn_To_gazoobraznoe.setFont(font)
        self.btn_To_gazoobraznoe.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #00f500;\n"
"}")
        self.btn_To_gazoobraznoe.setObjectName("btn_To_gazoobraznoe")
        self.btn_cancel = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cancel.setGeometry(QtCore.QRect(270, 310, 251, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.btn_cancel.setFont(font)
        self.btn_cancel.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #00f500;\n"
"}")
        self.btn_cancel.setObjectName("btn_cancel")
        Selection_tree.setCentralWidget(self.centralwidget)

        self.retranslateUi(Selection_tree)
        QtCore.QMetaObject.connectSlotsByName(Selection_tree)

    def retranslateUi(self, Selection_tree):
        _translate = QtCore.QCoreApplication.translate
        Selection_tree.setWindowTitle(_translate("Selection_tree", "MainWindow"))
        self.btn_To_zhidkoe.setText(_translate("Selection_tree", "ЖИДКОЕ ТОПЛИВО"))
        self.label.setText(_translate("Selection_tree", "Определение теплотворной способности топлива"))
        self.btn_To_gazoobraznoe.setText(_translate("Selection_tree", "ГАЗООБРАЗНОЕ ТОПЛИВО"))
        self.btn_cancel.setText(_translate("Selection_tree", "ЗАКРЫТЬ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Selection_tree = QtWidgets.QMainWindow()
    ui = Ui_Selection_tree()
    ui.setupUi(Selection_tree)
    Selection_tree.show()
    sys.exit(app.exec_())
